name: Test

on: push

jobs:
  ruby-test:
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.7
          - 3.0
          - 3.1
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run Tests
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
          COVERALLS_NOISY: true 
        run: bundle exec rspec --color --format documentation
